### ISSUE TITLE
As a registered user, I want to be able to login with my credentials.

### ISSUE THREAD

**Issue by nizonic** [sopra-fs23-group-34/server#1]
Acceptance criteria:
- [x] sopra-fs23-group-34/server#27
- [x] sopra-fs23-group-34/client#2
- [ ] sopra-fs23-group-34/server#35
