### ISSUE TITLE
As a Player in a running Game, I want to see a Timer and be able to make a guess before the Timer reaches zero.

### ISSUE THREAD

**Issue by nizonic** [sopra-fs23-group-34/server#11]
- [ ] sopra-fs23-group-34/client#21
- [ ] sopra-fs23-group-34/server#60
- [ ] sopra-fs23-group-34/client#20
