### ISSUE TITLE
As a user I want to be able to have some insight of my statistics.

### ISSUE THREAD

**Issue by nizonic** [sopra-fs23-group-34/server#14]
- [x] sopra-fs23-group-34/client#28
- [x] sopra-fs23-group-34/client#29
- [x] sopra-fs23-group-34/client#30
- [x] sopra-fs23-group-34/client#31
- [x] sopra-fs23-group-34/server#87
