### ISSUE TITLE
As an unregistered User, I want to be able to create a new account with my username, password and email.

### ISSUE THREAD

**Issue by nizonic** [sopra-fs23-group-34/server#2]
- [x] sopra-fs23-group-34/server#30
- [x] sopra-fs23-group-34/server#31
- [x] sopra-fs23-group-34/server#32
- [x] sopra-fs23-group-34/client#3
- [ ] sopra-fs23-group-34/server#34
