### ISSUE TITLE
As a logged in User, I want to be able to see and change my profile.

### ISSUE THREAD

**Issue by nizonic** [sopra-fs23-group-34/server#3]
- [ ] sopra-fs23-group-34/server#36
- [x] sopra-fs23-group-34/server#37
- [ ] sopra-fs23-group-34/server#38
- [x] sopra-fs23-group-34/client#4
