### ISSUE TITLE
As a logged in User, I want to be able to click on one of the following 6 Buttons on the Main Hub: Logout, edit my profile, individual stats, leaderboard, create a game, and join a game.

### ISSUE THREAD

**Issue by nizonic** [sopra-fs23-group-34/server#4]
- [x] sopra-fs23-group-34/client#5
- [x] sopra-fs23-group-34/client#6
- [x] sopra-fs23-group-34/client#7
- [x] sopra-fs23-group-34/client#8
- [ ] sopra-fs23-group-34/client#32 , sopra-fs23-group-34/server#14
- [ ] By clicking the leaderboard button, a user gets redirected to the leaderboard page, sopra-fs23-group-34/server#13 
- [x] sopra-fs23-group-34/server#44

**Comment by nizonic** [comment]
closed as of https://github.com/sopra-fs23-group-34/client/commit/8872b457fb7765e88a0254ba4d75cfdeef27c7e8
