### ISSUE TITLE
As a member of a running game, after each round, I want to see the correct values of each nutrient and see my guesses as well as those of all other players.

### ISSUE THREAD

**Issue by nizonic** [sopra-fs23-group-34/server#9]
- [ ] sopra-fs23-group-34/client#14
- [ ] sopra-fs23-group-34/client#15
- [ ] sopra-fs23-group-34/client#16
